root = "."
tmp_dir = "tmp"

[build]
cmd = "rm -f tmp/main && go build -o tmp/main ."
bin = "tmp/main"
exclude_dir = ["tmp", "vendor"]
include_ext = ["go", "tpl", "html"]
delay = 3000 # ms
stop_signal = "SIGTERM"
send_interrupt = false
kill_delay = 500 # ms