
# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/runner ./cmd/server"
bin = "tmp/runner"
include_ext = ["go", "tpl", "tmpl", "html"] # Added common template extensions
exclude_dir = [
  "tmp",
  "vendor",
  "frontend",
] # Added vendor and frontend for robustness

[log]
time = true
# Enable build and watcher logs explicitly
watcher = true
build = true

[color]
# Enable colors for better readability of Air's output
main = "cyan"
watcher = "green"
build = "yellow"
runner = "magenta"
app = "blue"

[runner]
# Ensure the runner is enabled (should be default, but explicit is good)
enable = true

[misc]
# Clean up temp directory on exit
clean_on_exit = true
